databases:
  - name: simple-airbnb-postgres-app-2kvm
    # databaseName: simple-airbnb-postgres-app
    # user: simple_airbnb_postgres_app_user

services:
  - type: web
    name: simple-airbnb-postgres-app-2kvm
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: simple-airbnb-postgres-app-2kvm
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false