databases:
  - name: simple-airbnb-postgres-app
    databaseName: simple-airbnb-postgres-app
    user: simple_airbnb_postgres_app_user

services:
  - type: web
    name: simple-airbnb-postgres-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false